try{
    hello();
} catch (error){
    console.log(error);
}

//lo nuevo

try{
    anotherFn();
} catch {
    console.log('Esto es un error.')
}